CREATE DATABASE LIVRARIA_RELATIVE2;

USE LIVRARIA_RELATIVE;

CREATE TABLE FORMATO (
    ID_FORMATO    INTEGER      NOT NULL PRIMARY KEY   AUTO_INCREMENT,
    TIPO          VARCHAR(20)  NOT NULL);


  
CREATE TABLE AUTOR (
    ID_AUTOR    INTEGER    NOT NULL PRIMARY KEY AUTO_INCREMENT,                              
    NOME_AUTOR  VARCHAR(100)         NOT NULL);
  

CREATE TABLE LIVRO (
    ID_LIVRO    INTEGER      NOT NULL   PRIMARY KEY AUTO_INCREMENT,
    TITULO     VARCHAR (200)    NOT NULL,           
    PRECO      FLOAT         NOT NULL, 
    ID_FORMATO   INTEGER     NOT NULL,  
    ID_AUTOR     INTEGER     NOT NULL,                    
    DATA_PUBLICACAO     DATE               NOT NULL,
    CONSTRAINT  fk_id_formato     FOREIGN KEY (ID_FORMATO) REFERENCES FORMATO(ID_FORMATO),
    CONSTRAINT  fk_id_autor       FOREIGN KEY (ID_AUTOR)   REFERENCES AUTOR(ID_AUTOR));

CREATE TABLE CATEGORIA (
   ID_CATEGORIA  INTEGER       NOT NULL  PRIMARY KEY AUTO_INCREMENT,
   GENERO        VARCHAR(50)   NOT NULL);

CREATE TABLE LIVRO_CATEGORIA (
   ID_LIVRO_CATEGORIA         INTEGER    NOT NULL PRIMARY KEY  AUTO_INCREMENT ,
   ID_LIVRO                   INTEGER    NOT NULL,
   ID_CATEGORIA               INTEGER    NOT NULL,
   CONSTRAINT  fk_id_livro     FOREIGN KEY (ID_LIVRO_CATEGORIA) REFERENCES LIVRO(ID_LIVRO),
   CONSTRAINT  fk_id_categoria     FOREIGN KEY (ID_LIVRO_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA));

CREATE TABLE VENDEDOR (
   ID_VENDEDOR  INTEGER       NOT NULL  PRIMARY KEY  AUTO_INCREMENT,                           
   NOME_VENDEDOR         VARCHAR(200)  NOT NULL,                                             
   CONTATO      VARCHAR(20)   NOT NULL);
  
CREATE TABLE CLIENTE (
   ID_CLIENTE        INTEGER    NOT NULL     PRIMARY KEY  AUTO_INCREMENT,     
   NUMERO_CELULAR    VARCHAR(20)          NOT NULL,         
   NOME              VARCHAR(200)        NOT NULL,              
   ANIVERSARIO       DATE,                     
   E_MAIL            VARCHAR(200)        NOT NULL);      
        

CREATE TABLE VENDA (
   ID_VENDA          INTEGER   NOT NULL  PRIMARY KEY   AUTO_INCREMENT,          
   ID_VENDEDOR       INTEGER   NOT NULL,     
   ID_CLIENTE        INTEGER   NOT NULL,
   DATA_VENDA        DATETIME  NOT NULL,
   VALOR             FLOAT     NOT NULL,
   CONSTRAINT  fk_id_vendedor  FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
   CONSTRAINT  fk_id_cliente   FOREIGN KEY(ID_CLIENTE)  REFERENCES CLIENTE(ID_CLIENTE));
        
CREATE TABLE LIVRO_VENDA ( 
   ID_LIVRO_VENDA     INTEGER   NOT NULL PRIMARY KEY  AUTO_INCREMENT,
   ID_LIVRO           INTEGER   NOT NULL,
   ID_VENDA           INTEGER   NOT NULL,
   N_ITENS            INTEGER   NOT NULL,
   CONSTRAINT  fk_id_livrovenda FOREIGN KEY (ID_LIVRO)  REFERENCES LIVRO(ID_LIVRO),
   CONSTRAINT  fk_id_vendalivro FOREIGN KEY (ID_VENDA)  REFERENCES VENDA(ID_VENDA));
      
							

CREATE TABLE LIVRO_AUTOR (
  ID_LIVRO_AUTOR  INTEGER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ID_LIVRO        INTEGER  NOT NULL, 
  ID_AUTOR        INTEGER  NOT NULL,
  CONSTRAINT  fk_id_livroautor FOREIGN KEY (ID_LIVRO)  REFERENCES LIVRO(ID_LIVRO),
  CONSTRAINT  fk_id_autorlivro FOREIGN KEY (ID_AUTOR)  REFERENCES AUTOR(ID_AUTOR)
); 



CREATE TABLE EDITORA (
  ID_EDITORA      INTEGER        NOT NULL PRIMARY KEY AUTO_INCREMENT,        
  NOME_EDITORA    VARCHAR(100)   NOT NULL);      
